import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | SoulDub.ai',
  description: 'Terms of service for SoulDub.ai.',
};

export default function TermsPage() {
  return (
    <>
      <h1 className="text-foreground mb-2 text-3xl font-bold">Terms of Service</h1>
      <p className="text-muted-foreground">
        <strong>Last updated: January 24, 2026</strong>
      </p>

      <h2>Agreement to Our Legal Terms</h2>
      <p>
        We are <strong>SoulDub.ai</strong> (&quot;<strong>we</strong>,&quot; &quot;
        <strong>us</strong>,&quot; or &quot;<strong>our</strong>&quot;). We operate
        the website <strong>https://www.souldub.ai</strong> (the &quot;
        <strong>Site</strong>&quot;), as well as any other related products and
        services that refer or link to these legal terms (the &quot;
        <strong>Legal Terms</strong>&quot;) (collectively, the &quot;
        <strong>Services</strong>&quot;). You can contact us by email at{' '}
        <strong>support@souldub.ai</strong>.
      </p>
      <p>
        These Legal Terms constitute a legally binding agreement made between you (
        &quot;<strong>you</strong>&quot;) and <strong>SoulDub.ai</strong>. You agree
        that by accessing the Services, you have read, understood, and agreed to be
        bound by all of these Legal Terms. <strong>
          IF YOU DO NOT AGREE WITH ALL OF THESE LEGAL TERMS, THEN YOU ARE EXPRESSLY
          PROHIBITED FROM USING THE SERVICES AND YOU MUST DISCONTINUE USE
          IMMEDIATELY.
        </strong>
      </p>

      <h2>Our Services</h2>
      <p>
        The information and tools provided through the Services are not intended for
        distribution to or use by any person in any jurisdiction where such use would
        be contrary to law. Those who choose to access the Services from other
        locations do so on their own initiative and are solely responsible for
        compliance with local laws.
      </p>

      <h2>Intellectual Property Rights &amp; Content Ownership</h2>
      <p>
        <strong>Our Intellectual Property:</strong> We own or license all source code,
        databases, software, website designs, audio, video, text, and graphics (the{' '}
        &quot;<strong>Content</strong>&quot;), and our trademarks (the &quot;
        <strong>Marks</strong>&quot;).
      </p>
      <p>
        <strong>User Content &amp; Ownership:</strong> You retain all ownership rights
        and copyright in the video, audio, or files you upload (&quot;
        <strong>User Content</strong>&quot;).
      </p>
      <p>
        <strong>Ownership of Output:</strong> Subject to your <strong>full payment</strong>{' '}
        of applicable service fees, SoulDub.ai hereby assigns to you all its rights,
        title, and interest in and to the output generated by the Services based on
        your User Content (&quot;<strong>Output</strong>&quot;). You are free to use
        and commercialize the Output.
      </p>
      <p>
        <strong>Our License to Your Content:</strong> You grant us a limited,
        non-exclusive license to process and host your User Content solely as
        necessary to provide and improve the Services. We do not claim any ownership
        over your User Content or Output.
      </p>

      <h2>User Representations</h2>
      <p>
        You warrant that: (1) your registration information is true; (2) you have
        legal capacity; (3) you are not a minor; (4) you will not use bots, scripts,
        or automated means to access the Services.
      </p>

      <h2>User Registration</h2>
      <p>
        You agree to keep your password confidential and are responsible for all use
        of your account and password. We reserve the right to remove or change a
        username if we determine it is inappropriate.
      </p>

      <h2>Purchases and Payment</h2>
      <p>
        We use third-party processors (such as <strong>Stripe</strong>) for payment.
        You agree to provide accurate purchase information. We may change prices at
        any time with 14 days&apos; notice. All payments are in <strong>US dollars</strong>.
      </p>

      <h2>Free Trial and Credits</h2>
      <p>
        We may offer complimentary credits or trial periods. These have no cash
        value, are not legal tender, and may be revoked or expired by us at any time
        without notice.
      </p>

      <h2>Cancellation and Refunds</h2>
      <p>
        <strong>Cancellation:</strong> You may cancel your subscription at any time
        via account settings. The cancellation will be effective at the conclusion of
        your current billing cycle.
      </p>
      <p>
        <strong>Refund Policy:</strong> Payments for subscription fees already made
        are <strong>non-refundable</strong>, unless required by applicable law.{' '}
        <strong>
          We do not provide refunds or credits for any unused or partially used
          subscription periods, nor for any unused credits or minutes after the
          billing cycle ends.
        </strong>{' '}
        By subscribing, you acknowledge that you are purchasing access to the
        Services for a specific duration, regardless of actual usage.
      </p>

      <h2>Prohibited Activities</h2>
      <p>
        You may not: (1) systematically retrieve data; (2) defraud or mislead us; (3)
        circumvent security; (4) use scripts or data mining tools; (5) upload viruses;
        (6) use the Services to compete with us.
      </p>

      <h2>User Generated Contributions</h2>
      <p>
        The Services may invite you to contribute content. You warrant that your
        Contributions do not infringe third-party rights (copyright, privacy, etc.).
        You are solely responsible for what you post or upload.
      </p>

      <h2>Contribution License</h2>
      <p>
        By submitting feedback or suggestions, you grant us a license to adapt,
        translate, and use your submissions to improve the Services. Your proprietary
        rights in your original submissions remain unchanged.
      </p>

      <h2>Third-Party Websites and Content</h2>
      <p>
        We are not responsible for any Third-Party Websites or Content linked from
        our Site. Use them at your own risk.
      </p>

      <h2>Services Management</h2>
      <p>
        We reserve the right to monitor the Services, take legal action against
        violators, and manage the Services to protect our rights and facilitate
        proper functioning.
      </p>

      <h2>Privacy Policy</h2>
      <p>
        Please review our Privacy Policy at{' '}
        <a href="/privacy">
          <strong>https://www.souldub.ai/privacy</strong>
        </a>
        . By using the Services, you agree to be bound by its terms.
      </p>

      <h2>Copyright Infringements</h2>
      <p>
        We respect the intellectual property rights of others. If you believe any
        material infringes upon your copyright, please notify us immediately at{' '}
        <strong>support@souldub.ai</strong>.
      </p>

      <h2>Term and Termination</h2>
      <p>
        These Legal Terms remain in effect while you use the Services. We reserve the
        right to deny access or delete your account at our sole discretion, without
        warning, for any reason.
      </p>

      <h2>Modifications and Interruptions</h2>
      <p>
        We cannot guarantee the Services will be available at all times. We are not
        liable for any loss caused by downtime, maintenance, or discontinuance.
      </p>

      <h2>Governing Law</h2>
      <p>
        These terms are governed by the laws applicable to the service provider,
        without regard to its conflict of law principles. Any dispute shall be
        resolved in the jurisdiction of the service provider.
      </p>

      <h2>Corrections</h2>
      <p>
        We reserve the right to correct typographical errors, inaccuracies, or
        omissions on the Site at any time without prior notice.
      </p>

      <h2>Export Compliance</h2>
      <p>
        You agree not to export our Services to any country or individual under trade
        embargoes or restricted lists in accordance with applicable export laws.
      </p>

      <h2>Disclaimer</h2>
      <p>
        <strong>
          THE SERVICES ARE PROVIDED &quot;AS-IS&quot; AND &quot;AS-AVAILABLE.&quot; WE
          DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY AND
          FITNESS FOR A PARTICULAR PURPOSE.
        </strong>
      </p>

      <h2>Limitations of Liability</h2>
      <p>
        <strong>
          IN NO EVENT WILL WE BE LIABLE FOR ANY DIRECT, INDIRECT, OR CONSEQUENTIAL
          DAMAGES. OUR LIABILITY TO YOU WILL BE LIMITED TO THE AMOUNT PAID BY YOU TO
          US DURING THE SIX (6) MONTH PERIOD PRIOR TO THE CAUSE OF ACTION.
        </strong>
      </p>

      <h2>Indemnification</h2>
      <p>
        You agree to defend and hold us harmless from any claims, damages, or demands
        arising out of your use of the Services or breach of these Legal Terms.
      </p>

      <h2>User Data</h2>
      <p>
        You are solely responsible for the data you transmit. We are not liable for
        any loss or corruption of such data.
      </p>

      <h2>Electronic Communications</h2>
      <p>
        You consent to receive electronic communications and agree that electronic
        signatures satisfy any legal requirement that such communication be in
        writing.
      </p>

      <h2>California Users and Residents</h2>
      <p>
        California residents may contact the Complaint Assistance Unit of the Division
        of Consumer Services for unresolved complaints.
      </p>

      <h2>Miscellaneous</h2>
      <p>
        These terms constitute the entire agreement. If any part is unenforceable,
        the remaining parts stay in effect. No joint venture or partnership is created
        by these Terms.
      </p>

      <h2>Supplemental Terms</h2>
      <p>
        Subject to these terms, we grant each user a non-exclusive license to use the
        Site content solely for the purpose of utilizing the Services.
      </p>

      <h2>Contact Us</h2>
      <p>
        For any complaints or further information, please contact us at:{' '}
        <strong>support@souldub.ai</strong>.
      </p>
    </>
  );
}

